services:
  # Web service (Express backend + React frontend)
  - type: web
    name: jobjet
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # User will need to set this in Render dashboard
      - key: SESSION_SECRET
        generateValue: true # Automatically generate a secure value
      - key: SERVER_URL
        fromService:
          name: jobjet
          type: web
          property: url
    healthCheckPath: /api/health
    autoDeploy: true

# Database configuration
databases:
  - name: jobjet-db
    plan: free # Can be upgraded as needed
    databaseName: jobjet
    user: jobjet_user